#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
full.tcl 文件生成器
负责合并多个 YAML 配置文件并生成 full.tcl 文件
"""

import sys
import yaml
import shutil
from pathlib import Path
from typing import Optional, Dict, Tuple
from tkinter import Tcl
from datetime import datetime
import logging

from edp_center.packages.edp_common import ValidationError, log_exception, EDPFileNotFoundError
from edp_center.packages.edp_common.error_handler import handle_error, error_context
from edp_center.packages.edp_common.exceptions import ConfigError

# 获取 logger
logger = logging.getLogger(__name__)

from .tcl_generator import build_config_file_paths
from .tcl_generator.path_builder import build_output_path
from .tcl_generator.tcl_file_processor import process_tcl_file
from .tcl_generator.yaml_file_processor import process_yaml_file
from .tcl_generator.variable_writer import write_file_variables
from .tcl_generator.type_info_writer import write_type_info
from .tcl_generator.variable_protection import generate_variable_protection_code
from .tcl_generator.variable_validator import validate_file_variables_are_arrays, validate_all_variables_are_arrays
from .tcl_generator.auto_variables import write_auto_variables
from .tcl_generator.constraint_validator import validate_full_tcl_constraints


@handle_error(error_message="生成 full.tcl 失败", reraise=True)
def generate_full_tcl(edp_center_path: Path, foundry: str, node: str, project: Optional[str],
                      work_path_info: Optional[Dict], flow_name: str, step_name: str, 
                      current_dir: Optional[Path] = None) -> Tuple[Optional[Path], Optional[Path]]:
    """
    生成 full.tcl 文件，合并所有配置 YAML 文件
    
    Args:
        edp_center_path: edp_center 路径
        foundry: 代工厂名称
        node: 工艺节点
        project: 项目名称（可选）
        work_path_info: 工作路径信息字典（可选）
        flow_name: 流程名称
        step_name: 步骤名称
        current_dir: 当前目录（可选，用于查找 user_config.yaml）
        
    Returns:
        (full.tcl 文件路径, 备份文件路径) 的元组
        - full.tcl 文件路径：新生成的 full.tcl 路径
        - 备份文件路径：如果存在备份，返回备份文件路径；否则返回 None
        如果生成失败则返回 (None, None)
    """
    # 构建所有 YAML 文件路径（按优先级顺序）
    config_files = build_config_file_paths(
        edp_center_path, foundry, node, project, work_path_info, flow_name, current_dir
    )
    
    if not config_files:
        # 没有找到任何配置文件，抛出异常
        # 构建详细的解决建议
        suggestion_parts = [
                "请检查配置文件路径是否正确，确保配置文件存在于正确的位置：",
                "",
                "配置文件查找路径（按优先级顺序）：",
                "1. user_config.yaml（当前目录或工作目录）",
                f"2. {foundry}/{node}/{project or 'common'}/{flow_name}/{step_name}.yaml",
                f"3. {foundry}/{node}/{project or 'common'}/{flow_name}/common.yaml",
                f"4. {foundry}/{node}/{project or 'common'}/common.yaml",
                f"5. {foundry}/{node}/common/common.yaml",
                f"6. {foundry}/common/common.yaml",
                "",
                "检查步骤：",
                f"1. 确认 edp_center 路径正确: {edp_center_path}",
                f"2. 确认 foundry 和 node 正确: {foundry}/{node}",
                f"3. 确认项目路径正确: {project or 'common'}",
                f"4. 确认流程和步骤名称正确: {flow_name}.{step_name}",
                "",
                "如果配置文件不存在，可以：",
                "1. 创建对应的配置文件",
                "2. 使用 'edp_init' 初始化项目结构",
                "3. 检查配置文件是否在正确的位置"
        ]
        
        raise ConfigError(
            "未找到任何配置文件，无法生成 full.tcl",
            config_path=str(edp_center_path / "config"),
            context={
                "edp_center_path": str(edp_center_path),
                "foundry": foundry,
                "node": node,
                "project": project,
                "flow_name": flow_name,
                "step_name": step_name,
                "current_dir": str(current_dir) if current_dir else None
            },
            suggestion="\n".join(suggestion_parts)
        )
    
    # 构建输出文件路径
    full_tcl_path = build_output_path(work_path_info, flow_name, step_name, current_dir)
    
    # 创建一个共享的 Tcl interpreter，用于累积所有变量
    shared_interp = Tcl()
    # 只在第一次初始化类型信息数组
    shared_interp.eval("array set __configkit_types__ {}")
    
    # 打开输出文件，准备写入
    with open(full_tcl_path, 'w', encoding='utf-8') as f:
        # 写入文件头
        f.write("# Generated by configkit\n")
        f.write("# Merged from the following files (in order, later files override earlier ones):\n")
        for config_file in config_files:
            abs_path = Path(config_file).resolve()
            f.write(f"#   - {abs_path}\n")
        f.write("\n")
        
        # 逐个读取和转换配置文件（YAML 或 Tcl），转换后立即输出
        for config_file in config_files:
            try:
                config_file_path = Path(config_file)
                abs_path = config_file_path.resolve()
                
                # 根据文件扩展名选择解析方式
                if config_file_path.suffix.lower() == '.tcl':
                    # 处理 Tcl 文件
                    temp_interp = process_tcl_file(config_file_path, shared_interp)
                else:
                    # 处理 YAML 文件（默认）
                    temp_interp = process_yaml_file(config_file_path, shared_interp)
                    if temp_interp is None:
                        # 文件为空，跳过
                        continue
                
                # 验证该文件定义的变量都是数组格式（带命名空间）
                # 如果验证失败，validate_file_variables_are_arrays 会抛出 ValidationError
                validate_file_variables_are_arrays(temp_interp, abs_path)
                
                # 立即输出该文件定义的变量
                write_file_variables(shared_interp, temp_interp, abs_path, f)
                
            except (yaml.YAMLError, ConfigError, ValidationError):
                # YAML 解析错误、配置错误和验证错误已经在各自的处理函数中处理了，这里重新抛出
                raise
            except Exception as e:
                # 其他错误（如文件读取失败），输出警告但继续处理其他文件
                # 使用 error_context 统一处理，但不中断流程
                with error_context(error_message=f"处理配置文件失败: {abs_path}", log_error=True, reraise=False):
                    raise ConfigError(
                        f"处理配置文件时发生错误: {e}",
                        config_file=str(abs_path),
                        suggestion="请检查文件是否存在且可读"
                    ) from e
                # 如果到达这里，说明错误已被处理，继续处理下一个文件
                continue
        
        # 验证所有变量都是数组格式（带命名空间）
        # 如果验证失败，validate_all_variables_are_arrays 会抛出 ValidationError
        validate_all_variables_are_arrays(shared_interp)
        
        # 重新写入自动生成的变量（确保它们不被配置文件覆盖）
        # 这些变量应该在最后，确保它们的值不会被配置文件覆盖
        f.write("\n")  # 在自动生成的变量之前添加空行，与配置文件变量分隔
        write_auto_variables(
            work_path_info, foundry, node, project,
            flow_name, step_name, full_tcl_path, edp_center_path, f
        )
        
        # 生成变量保护代码（如果存在新格式变量）
        generate_variable_protection_code(shared_interp, f)
        
        # 导出类型信息（如果可用）
        write_type_info(shared_interp, f)
    
    # 检查是否成功创建了文件
    if full_tcl_path and full_tcl_path.exists():
        # 🔥 新增：生成 full.tcl 后，立即验证 constraint
        try:
            validate_full_tcl_constraints(full_tcl_path, config_files, edp_center_path)
        except ValidationError as e:
            # 用户输出（友好格式，保持原有行为）
            print(str(e), file=sys.stderr)
            
            # 日志记录（结构化数据）
            if log_exception:
                log_exception(logger, e)
            else:
                logger.error(f"配置验证失败: {e.message}", exc_info=True)
            
            raise
        
        # ==================== 配置快照：生成后立即备份 ====================
        # 时机：在生成新的 full.tcl 之后
        # 目的：每次运行都有独立的配置快照，不依赖之前的运行
        # 
        # 流程：
        # 1. 生成新的 full.tcl（用于本次实际执行）
        # 2. 立即备份这个新生成的 full.tcl（这是本次运行的配置快照）
        # 3. 备份文件的路径将记录到 .run_info 中
        #
        # 这样每次运行都是独立的，即使后续运行覆盖了 full.tcl，也能找到本次运行的配置
        backup_path = None
        try:
            # 创建备份目录
            backup_dir = full_tcl_path.parent / 'backups'
            backup_dir.mkdir(exist_ok=True)
            
            # 生成备份文件名（带时间戳，格式：full_YYYYMMDD_HHMMSS.tcl）
            # 时间戳是运行开始时间，用于标识本次运行的配置快照
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            backup_name = f"full_{timestamp}.tcl"
            backup_path = backup_dir / backup_name
            
            # 备份刚生成的 full.tcl（这是本次运行的配置快照）
            shutil.copy2(full_tcl_path, backup_path)
            logger.info(f"已创建配置快照: {backup_path}（本次运行的配置）")
        except Exception as e:
            # 如果备份失败，记录警告但继续执行
            logger.warning(f"备份 full.tcl 失败: {e}，将只记录 full.tcl 路径")
            backup_path = None
        
        # 返回 (full.tcl 路径, 备份文件路径)
        # 备份路径将记录到 .run_info 中，用于后续的配置对比
        return (full_tcl_path, backup_path)
    else:
        # full.tcl 文件未成功创建，抛出异常
        raise EDPFileNotFoundError(
            f"full.tcl 文件未成功创建: {full_tcl_path}",
            file_path=str(full_tcl_path),
            suggestion="请检查文件系统权限和磁盘空间"
        )
