#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
full.tcl 文件生成器
负责合并多个 YAML 配置文件并生成 full.tcl 文件
"""

import sys
import yaml
from pathlib import Path
from typing import Optional, Dict
from tkinter import Tcl
import logging

from edp_center.packages.edp_common import ValidationError, log_exception

# 获取 logger
logger = logging.getLogger(__name__)

from .tcl_generator import build_config_file_paths
from .tcl_generator.path_builder import build_output_path
from .tcl_generator.tcl_file_processor import process_tcl_file
from .tcl_generator.yaml_file_processor import process_yaml_file
from .tcl_generator.variable_writer import write_file_variables
from .tcl_generator.type_info_writer import write_type_info
from .tcl_generator.variable_protection import generate_variable_protection_code
from .tcl_generator.variable_validator import validate_file_variables_are_arrays, validate_all_variables_are_arrays
from .tcl_generator.auto_variables import write_auto_variables
from .tcl_generator.constraint_validator import validate_full_tcl_constraints


def generate_full_tcl(edp_center_path: Path, foundry: str, node: str, project: Optional[str],
                      work_path_info: Optional[Dict], flow_name: str, step_name: str, 
                      current_dir: Optional[Path] = None) -> Optional[Path]:
    """
    生成 full.tcl 文件，合并所有配置 YAML 文件
    
    Args:
        edp_center_path: edp_center 路径
        foundry: 代工厂名称
        node: 工艺节点
        project: 项目名称（可选）
        work_path_info: 工作路径信息字典（可选）
        flow_name: 流程名称
        step_name: 步骤名称
        current_dir: 当前目录（可选，用于查找 user_config.yaml）
        
    Returns:
        full.tcl 文件路径，如果生成失败则返回 None
    """
    try:
        # 构建所有 YAML 文件路径（按优先级顺序）
        config_files = build_config_file_paths(
            edp_center_path, foundry, node, project, work_path_info, flow_name, current_dir
        )
        
        if not config_files:
            # 没有找到任何配置文件，返回 None
            print(f"[WARN] 未找到任何配置文件，无法生成 full.tcl", file=sys.stderr)
            logger.warning("未找到任何配置文件，无法生成 full.tcl")
            return None
        
        # 构建输出文件路径
        full_tcl_path = build_output_path(work_path_info, flow_name, step_name, current_dir)
        
        # 创建一个共享的 Tcl interpreter，用于累积所有变量
        shared_interp = Tcl()
        # 只在第一次初始化类型信息数组
        shared_interp.eval("array set __configkit_types__ {}")
        
        # 打开输出文件，准备写入
        with open(full_tcl_path, 'w', encoding='utf-8') as f:
            # 写入文件头
            f.write("# Generated by configkit\n")
            f.write("# Merged from the following files (in order, later files override earlier ones):\n")
            for config_file in config_files:
                abs_path = Path(config_file).resolve()
                f.write(f"#   - {abs_path}\n")
            f.write("\n")
            
            # 逐个读取和转换配置文件（YAML 或 Tcl），转换后立即输出
            for config_file in config_files:
                try:
                    config_file_path = Path(config_file)
                    abs_path = config_file_path.resolve()
                    
                    # 根据文件扩展名选择解析方式
                    if config_file_path.suffix.lower() == '.tcl':
                        # 处理 Tcl 文件
                        temp_interp = process_tcl_file(config_file_path, shared_interp)
                    else:
                        # 处理 YAML 文件（默认）
                        temp_interp = process_yaml_file(config_file_path, shared_interp)
                        if temp_interp is None:
                            # 文件为空，跳过
                            continue
                    
                    # 验证该文件定义的变量都是数组格式（带命名空间）
                    try:
                        validate_file_variables_are_arrays(temp_interp, abs_path)
                    except ValueError as e:
                        # 发现简单变量，输出错误信息并抛出异常
                        print(f"[ERROR] 变量格式验证失败:", file=sys.stderr)
                        print(str(e), file=sys.stderr)
                        logger.error(f"变量格式验证失败: {e}", extra={'config_file': str(abs_path)})
                        raise
                    
                    # 立即输出该文件定义的变量
                    write_file_variables(shared_interp, temp_interp, abs_path, f)
                    
                except yaml.YAMLError:
                    # YAML 解析错误已经在 process_yaml_file 中处理了，这里重新抛出
                    raise
                except Exception as e:
                    # 其他错误（如文件读取失败），输出错误信息但继续处理其他文件
                    abs_path = Path(config_file).resolve()
                    print(f"[WARN] 处理配置文件失败: {abs_path}", file=sys.stderr)
                    print(f"[WARN] 错误信息: {e}", file=sys.stderr)
                    print(f"[WARN] 跳过该文件，继续处理其他文件", file=sys.stderr)
                    logger.warning(f"处理配置文件失败: {abs_path}", exc_info=True, extra={'config_file': str(abs_path), 'error': str(e)})
                    continue
            
            # 验证所有变量都是数组格式（带命名空间）
            try:
                validate_all_variables_are_arrays(shared_interp)
            except ValueError as e:
                # 发现简单变量，输出错误信息并抛出异常
                print(f"[ERROR] 变量格式验证失败:", file=sys.stderr)
                print(str(e), file=sys.stderr)
                logger.error(f"变量格式验证失败: {e}", exc_info=True)
                raise
            
            # 重新写入自动生成的变量（确保它们不被配置文件覆盖）
            # 这些变量应该在最后，确保它们的值不会被配置文件覆盖
            f.write("\n")  # 在自动生成的变量之前添加空行，与配置文件变量分隔
            write_auto_variables(
                work_path_info, foundry, node, project,
                flow_name, step_name, full_tcl_path, edp_center_path, f
            )
            
            # 生成变量保护代码（如果存在新格式变量）
            generate_variable_protection_code(shared_interp, f)
            
            # 导出类型信息（如果可用）
            write_type_info(shared_interp, f)
        
        # 检查是否成功创建了文件
        if full_tcl_path and full_tcl_path.exists():
            # 🔥 新增：生成 full.tcl 后，立即验证 constraint
            try:
                validate_full_tcl_constraints(full_tcl_path, config_files, edp_center_path)
            except ValidationError as e:
                # 用户输出（友好格式，保持原有行为）
                print(str(e), file=sys.stderr)
                
                # 日志记录（结构化数据）
                if log_exception:
                    log_exception(logger, e)
                else:
                    logger.error(f"配置验证失败: {e.message}", exc_info=True)
                
                raise
            
            return full_tcl_path
        else:
            print(f"[WARN] full.tcl 文件未成功创建: {full_tcl_path}", file=sys.stderr)
            logger.warning(f"full.tcl 文件未成功创建: {full_tcl_path}")
            return None
        
    except ValueError as e:
        # 变量格式验证失败，直接抛出异常，不捕获
        # 这样调用者可以知道是验证失败，而不是其他错误
        logger.error(f"变量格式验证失败: {e}", exc_info=True)
        raise
    except (OSError, IOError, yaml.YAMLError) as e:
        # 文件操作错误或 YAML 解析错误
        print(f"[ERROR] 生成 full.tcl 失败: {e}", file=sys.stderr)
        logger.error(f"生成 full.tcl 失败: {e}", exc_info=True)
        return None
    except Exception as e:
        # 其他未预期的错误
        print(f"[ERROR] 生成 full.tcl 时发生未预期的错误: {e}", file=sys.stderr)
        logger.exception("生成 full.tcl 时发生未预期的错误")
        return None
