# Generated by configkit
# Merged from the following files (in order, later files override earlier ones):
#   - C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\common\main\init_project.yaml
#   - C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\common\main\config.yaml
#   - C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\common\pv_calibre\config.yaml
#   - C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\dongting\main\init_project.yaml
#   - C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\dongting\main\config.yaml
#   - C:\Users\anping.chen\Desktop\EDP_AI\Example\WORK_PATH\dongting\P85\block1\user1\main\user_config.yaml

# Auto-generated project variables
set project(project_name) dongting
set project(version) P85
set project(block_name) block1
set project(user_name) user1
set project(branch_name) main
set project(foundry) SAMSUNG
set project(node) S8
set project(flow_name) pv_calibre
set project(step_name) ipmerge
set project(init_path) "C:\Users\anping.chen\Desktop\EDP_AI\Example\WORK_PATH"
set project(work_path) "C:\Users\anping.chen\Desktop\EDP_AI\Example\WORK_PATH\dongting\P85\block1\user1\main\runs\pv_calibre.ipmerge"
set edp(edp_center_path) "C:\Users\anping.chen\Desktop\EDP_AI\edp_center"
set edp(config_path) "C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config"
set edp(flow_path) "C:\Users\anping.chen\Desktop\EDP_AI\edp_center\flow"


# From C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\common\main\init_project.yaml
set edp(branch_template,directories) {cmds dbs flow hooks logs rpts runs}
set edp(branch_template,files) {user_config.tcl user_config.yaml}
set project(allowed_work_paths) {}
set project(blocks) {{name block1 description 块1} {name block2 description 块2}}
set project(node_naming_pattern) {P{number}}
set project(work_path_name) WORK_PATH

# From C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\common\main\config.yaml
set pv_calibre(default,cpu_num) 16
set pv_calibre(default,lsf) 1
set pv_calibre(default,lsf_opt) -Ip
set pv_calibre(default,memory) 10000
set pv_calibre(default,pre_lsf) {}
set pv_calibre(default,queue) default
set pv_calibre(default,span) 1
set pv_calibre(default,tool_opt) {calibre -64 -batch}
set pv_calibre(ipmerge,cpu_num) 16
set pv_calibre(ipmerge,lsf) 1
set pv_calibre(ipmerge,queue) default
set pv_calibre(test_py,lsf) 0
set pv_calibre(test_py,tool_opt) python

# From C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\common\pv_calibre\config.yaml
set project(allowed_work_paths) {}
set project(blocks) {{name block1 description 块1} {name block2 description 块2}}
set project(node_naming_pattern) {P{number}}
set project(test_var) 1
set project(work_path_name) WORK_PATH

# From C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\dongting\main\init_project.yaml
set project(allowed_work_paths) {}
set project(blocks) {{name block1 description {dongting 项目块1}} {name block2 description {dongting 项目块2}}}
set project(node_naming_pattern) {P{number}}
set project(test_var) 1
set project(work_path_name) WORK_PATH
# Auto-generated project variables
set project(project_name) dongting
set project(version) P85
set project(block_name) block1
set project(user_name) user1
set project(branch_name) main
set project(foundry) SAMSUNG
set project(node) S8
set project(flow_name) pv_calibre
set project(step_name) ipmerge
set project(init_path) "C:\Users\anping.chen\Desktop\EDP_AI\Example\WORK_PATH"
set project(work_path) "C:\Users\anping.chen\Desktop\EDP_AI\Example\WORK_PATH\dongting\P85\block1\user1\main\runs\pv_calibre.ipmerge"
set edp(edp_center_path) "C:\Users\anping.chen\Desktop\EDP_AI\edp_center"
set edp(config_path) "C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config"
set edp(flow_path) "C:\Users\anping.chen\Desktop\EDP_AI\edp_center\flow"


# Type information for configkit
array set __configkit_types__ {}
set __configkit_types__(edp(branch_template,directories)) list
set __configkit_types__(edp(branch_template,files)) list
set __configkit_types__(project(allowed_work_paths)) list
set __configkit_types__(project(blocks)) list
set __configkit_types__(project(node_naming_pattern)) string
set __configkit_types__(project(test_var)) number
set __configkit_types__(project(work_path_name)) string
set __configkit_types__(pv_calibre(default,cpu_num)) number
set __configkit_types__(pv_calibre(default,lsf)) number
set __configkit_types__(pv_calibre(default,lsf_opt)) string
set __configkit_types__(pv_calibre(default,memory)) number
set __configkit_types__(pv_calibre(default,pre_lsf)) string
set __configkit_types__(pv_calibre(default,queue)) string
set __configkit_types__(pv_calibre(default,span)) number
set __configkit_types__(pv_calibre(default,tool_opt)) string
set __configkit_types__(pv_calibre(ipmerge,cpu_num)) number
set __configkit_types__(pv_calibre(ipmerge,lsf)) number
set __configkit_types__(pv_calibre(ipmerge,queue)) string
set __configkit_types__(pv_calibre(test_py,lsf)) number
set __configkit_types__(pv_calibre(test_py,tool_opt)) string
