# Generated by configkit
# Merged from the following files (in order, later files override earlier ones):
#   - C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\common\main\init_project.yaml
#   - C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\common\main\config.yaml
#   - C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\dongting\main\init_project.yaml
#   - C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\dongting\main\config.yaml
#   - C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\dongting\pnr_innovus\config.yaml
#   - C:\Users\anping.chen\Desktop\EDP_AI\Example\WORK_PATH\dongting\P111\B1\anping.chen\firest\user_config.yaml


# From C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\common\main\init_project.yaml
set edp(branch_template,directories) {cmds dbs flow hooks logs rpts runs}
set edp(branch_template,files) {user_config.tcl user_config.yaml}
set project(allowed_work_paths) {}
set project(blocks) {{name block1 description 块1} {name block2 description 块2}}
set project(node_naming_pattern) {P{number}}
set project(work_path_name) WORK_PATH

# From C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\common\main\config.yaml
set pv_calibre(default,cpu_num) 16
set pv_calibre(default,lsf) 1
set pv_calibre(default,lsf_opt) -Ip
set pv_calibre(default,memory) 10000
set pv_calibre(default,pre_lsf) {}
set pv_calibre(default,queue) default
set pv_calibre(default,span) 1
set pv_calibre(default,tool_opt) {calibre -64 -batch}
set pv_calibre(ipmerge,cpu_num) 16
set pv_calibre(ipmerge,lsf) 1
set pv_calibre(ipmerge,queue) default
set pv_calibre(test_py,lsf) 0
set pv_calibre(test_py,tool_opt) python

# From C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\dongting\main\init_project.yaml
set project(allowed_work_paths) {}
set project(blocks) {{name block1 description {dongting 项目块1}} {name block2 description {dongting 项目块2}}}
set project(node_naming_pattern) {P{number}}
set project(work_path_name) WORK_PATH

# From C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config\SAMSUNG\S8\dongting\pnr_innovus\config.yaml
set pnr_innovus(default,cpu_num) 16
set pnr_innovus(default,lsf) 1
set pnr_innovus(default,lsf_max_wait_time) 86400
set pnr_innovus(default,lsf_opt) {}
set pnr_innovus(default,lsf_poll_interval) 30
set pnr_innovus(default,memory) 8000
set pnr_innovus(default,pre_lsf) {}
set pnr_innovus(default,queue) normal
set pnr_innovus(default,span) 1
set pnr_innovus(default,tool_opt) {innovus -file}
set pnr_innovus(default,wait_lsf) 1
set pnr_innovus(floorplan,memory) 16000
set pnr_innovus(floorplan,queue) high_mem
set pnr_innovus(place,cpu_num) 32
set pnr_innovus(place,memory) 12000
set pnr_innovus(postroute,cpu_num) 32
set pnr_innovus(postroute,memory) 16000
set pnr_innovus(postroute,queue) high_mem
set pnr_innovus(route,cpu_num) 64
set pnr_innovus(route,lsf_opt) -Ip
set pnr_innovus(route,memory) 24000
set pnr_innovus(route,wait_lsf) 0
set release(file_mappings,config) {**/*.mmc.tcl **/*.sdc config/**/*.tcl}
set release(file_mappings,db) **/*.db
set release(file_mappings,def) **/*.def
set release(file_mappings,hcell) **/*.hcell
set release(file_mappings,ilm) **/*.ilm
set release(file_mappings,lef) **/*.lef
set release(file_mappings,oas) **/*.oas
set release(file_mappings,sdf) **/*.sdf
set release(file_mappings,spef) **/*.spef
set release(file_mappings,timing) timing/**/*.csv
set release(file_mappings,upf) **/*.upf
set release(file_mappings,verilog) {**/*.v **/*.vg}
set release(keep_structure) {timing config lib}
set release(step_rules,floorplan,file_mappings,config) {config/*.tcl config/*.sdc}
set release(step_rules,floorplan,file_mappings,db) output/*.db
set release(step_rules,floorplan,file_mappings,def) *.def
set release(step_rules,floorplan,file_mappings,sdf) {}
set release(step_rules,floorplan,file_mappings,spef) {}
set release(step_rules,floorplan,file_mappings,verilog) {}
set release(step_rules,place,file_mappings,config) {**/*.mmc.tcl config/*.sdc}
set release(step_rules,place,file_mappings,db) output/*.db
set release(step_rules,place,file_mappings,def) {*.def output/*.def}
set release(step_rules,place,file_mappings,timing) {timing/place.csv timing/**/*.csv}
set release(step_rules,postroute,file_mappings,config) {**/*.mmc.tcl config/*.sdc}
set release(step_rules,postroute,file_mappings,db) output/*.db
set release(step_rules,postroute,file_mappings,def) {*.def output/*.def}
set release(step_rules,postroute,file_mappings,sdf) results/*.sdf
set release(step_rules,postroute,file_mappings,spef) results/*.spef
set release(step_rules,postroute,file_mappings,timing) {timing/postroute.csv timing/**/*.csv}
set release(step_rules,postroute,file_mappings,verilog) {netlist/*.v netlist/*.vg}

# Auto-generated project variables
set project(project_name) dongting
set project(version) P111
set project(block_name) B1
set project(user_name) anping.chen
set project(branch_name) firest
set project(foundry) SAMSUNG
set project(node) S8
set project(flow_name) pnr_innovus
set project(step_name) place
set project(init_path) "C:\Users\anping.chen\Desktop\EDP_AI\Example\WORK_PATH"
set project(work_path) "C:\Users\anping.chen\Desktop\EDP_AI\Example\WORK_PATH\dongting\P111\B1\anping.chen\firest\runs\pnr_innovus.place"
set edp(edp_center_path) "C:\Users\anping.chen\Desktop\EDP_AI\edp_center"
set edp(config_path) "C:\Users\anping.chen\Desktop\EDP_AI\edp_center\config"
set edp(flow_path) "C:\Users\anping.chen\Desktop\EDP_AI\edp_center\flow"
set edp(execution_plan,place) {pnr_innovus::restore_design pnr_innovus::config_design pnr_innovus::add_tie_cell pnr_innovus::save_design pnr_innovus::report_design pnr_innovus::check_pd pnr_innovus::save_metrics}


# Type information for configkit
array set __configkit_types__ {}
set __configkit_types__(edp(branch_template,directories)) list
set __configkit_types__(edp(branch_template,files)) list
set __configkit_types__(pnr_innovus(default,cpu_num)) number
set __configkit_types__(pnr_innovus(default,lsf)) number
set __configkit_types__(pnr_innovus(default,lsf_max_wait_time)) number
set __configkit_types__(pnr_innovus(default,lsf_opt)) string
set __configkit_types__(pnr_innovus(default,lsf_poll_interval)) number
set __configkit_types__(pnr_innovus(default,memory)) number
set __configkit_types__(pnr_innovus(default,pre_lsf)) string
set __configkit_types__(pnr_innovus(default,queue)) string
set __configkit_types__(pnr_innovus(default,span)) number
set __configkit_types__(pnr_innovus(default,tool_opt)) string
set __configkit_types__(pnr_innovus(default,wait_lsf)) bool
set __configkit_types__(pnr_innovus(floorplan,memory)) number
set __configkit_types__(pnr_innovus(floorplan,queue)) string
set __configkit_types__(pnr_innovus(place,cpu_num)) number
set __configkit_types__(pnr_innovus(place,memory)) number
set __configkit_types__(pnr_innovus(postroute,cpu_num)) number
set __configkit_types__(pnr_innovus(postroute,memory)) number
set __configkit_types__(pnr_innovus(postroute,queue)) string
set __configkit_types__(pnr_innovus(route,cpu_num)) number
set __configkit_types__(pnr_innovus(route,lsf_opt)) string
set __configkit_types__(pnr_innovus(route,memory)) number
set __configkit_types__(pnr_innovus(route,wait_lsf)) bool
set __configkit_types__(project(allowed_work_paths)) list
set __configkit_types__(project(blocks)) list
set __configkit_types__(project(node_naming_pattern)) string
set __configkit_types__(project(work_path_name)) string
set __configkit_types__(pv_calibre(default,cpu_num)) number
set __configkit_types__(pv_calibre(default,lsf)) number
set __configkit_types__(pv_calibre(default,lsf_opt)) string
set __configkit_types__(pv_calibre(default,memory)) number
set __configkit_types__(pv_calibre(default,pre_lsf)) string
set __configkit_types__(pv_calibre(default,queue)) string
set __configkit_types__(pv_calibre(default,span)) number
set __configkit_types__(pv_calibre(default,tool_opt)) string
set __configkit_types__(pv_calibre(ipmerge,cpu_num)) number
set __configkit_types__(pv_calibre(ipmerge,lsf)) number
set __configkit_types__(pv_calibre(ipmerge,queue)) string
set __configkit_types__(pv_calibre(test_py,lsf)) number
set __configkit_types__(pv_calibre(test_py,tool_opt)) string
set __configkit_types__(release(file_mappings,config)) string
set __configkit_types__(release(file_mappings,db)) string
set __configkit_types__(release(file_mappings,def)) string
set __configkit_types__(release(file_mappings,hcell)) string
set __configkit_types__(release(file_mappings,ilm)) string
set __configkit_types__(release(file_mappings,lef)) string
set __configkit_types__(release(file_mappings,oas)) string
set __configkit_types__(release(file_mappings,sdf)) string
set __configkit_types__(release(file_mappings,spef)) string
set __configkit_types__(release(file_mappings,timing)) string
set __configkit_types__(release(file_mappings,upf)) string
set __configkit_types__(release(file_mappings,verilog)) string
set __configkit_types__(release(keep_structure)) list
set __configkit_types__(release(step_rules,floorplan,file_mappings,config)) string
set __configkit_types__(release(step_rules,floorplan,file_mappings,db)) string
set __configkit_types__(release(step_rules,floorplan,file_mappings,def)) string
set __configkit_types__(release(step_rules,floorplan,file_mappings,sdf)) none
set __configkit_types__(release(step_rules,floorplan,file_mappings,spef)) none
set __configkit_types__(release(step_rules,floorplan,file_mappings,verilog)) none
set __configkit_types__(release(step_rules,place,file_mappings,config)) string
set __configkit_types__(release(step_rules,place,file_mappings,db)) string
set __configkit_types__(release(step_rules,place,file_mappings,def)) string
set __configkit_types__(release(step_rules,place,file_mappings,timing)) string
set __configkit_types__(release(step_rules,postroute,file_mappings,config)) string
set __configkit_types__(release(step_rules,postroute,file_mappings,db)) string
set __configkit_types__(release(step_rules,postroute,file_mappings,def)) string
set __configkit_types__(release(step_rules,postroute,file_mappings,sdf)) string
set __configkit_types__(release(step_rules,postroute,file_mappings,spef)) string
set __configkit_types__(release(step_rules,postroute,file_mappings,timing)) string
set __configkit_types__(release(step_rules,postroute,file_mappings,verilog)) string
